/// Flutter icons Icon_custom
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon_custom
///      fonts:
///       - asset: fonts/Icon_custom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Icon_custom {
  Icon_custom._();

  static const _kFontFam = 'Icon_custom';
  static const String? _kFontPkg = null;

  static const IconData juice = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icecream = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fries = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allfoods = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
